version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    ports:
        - "9005:1521" 
        - "9006:8080"
    environment:
      ORACLE_PASSWORD: 12345
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ords/"]
      interval: 30s
      timeout: 10s
      retries: 10
    restart: unless-stopped